// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence.DataContext;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(FuelPointerDbContext))]
    [Migration("20240110230248_teste")]
    partial class teste
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Domain.Entities.DepartureLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("FuelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReferencePoint")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UF")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FuelId")
                        .IsUnique();

                    b.ToTable("Tb_DepartureLocations");
                });

            modelBuilder.Entity("Domain.Entities.Destination", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("FuelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReferencePoint")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UF")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FuelId")
                        .IsUnique();

                    b.ToTable("Tb_Destinations");
                });

            modelBuilder.Entity("Domain.Entities.Fuel", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("DateDeleted")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("DateUpdate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("IdFuel")
                        .HasColumnType("int");

                    b.Property<double>("QuantityOfLiters")
                        .HasColumnType("float");

                    b.Property<string>("SupplyDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ValuePerLiter")
                        .HasColumnType("float");

                    b.Property<Guid?>("Vehicleid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("departureLocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("destinationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("typeFuel")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("IdFuel")
                        .IsUnique();

                    b.HasIndex("Vehicleid");

                    b.ToTable("Tb_Fuels");
                });

            modelBuilder.Entity("Domain.Entities.Vehicle", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("DateDeleted")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("DateUpdate")
                        .HasColumnType("datetimeoffset");

                    b.Property<double>("KmPerLiter")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Plate")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("char(7)");

                    b.HasKey("id");

                    b.HasIndex("Plate")
                        .IsUnique();

                    b.ToTable("Tb_Vehicles");
                });

            modelBuilder.Entity("Domain.Entities.DepartureLocation", b =>
                {
                    b.HasOne("Domain.Entities.Fuel", "Fuel")
                        .WithOne("departureLocation")
                        .HasForeignKey("Domain.Entities.DepartureLocation", "FuelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fuel");
                });

            modelBuilder.Entity("Domain.Entities.Destination", b =>
                {
                    b.HasOne("Domain.Entities.Fuel", "Fuel")
                        .WithOne("destination")
                        .HasForeignKey("Domain.Entities.Destination", "FuelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fuel");
                });

            modelBuilder.Entity("Domain.Entities.Fuel", b =>
                {
                    b.HasOne("Domain.Entities.Vehicle", null)
                        .WithMany("Fuel")
                        .HasForeignKey("Vehicleid");
                });

            modelBuilder.Entity("Domain.Entities.Fuel", b =>
                {
                    b.Navigation("departureLocation")
                        .IsRequired();

                    b.Navigation("destination")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Vehicle", b =>
                {
                    b.Navigation("Fuel");
                });
#pragma warning restore 612, 618
        }
    }
}
